"""
Script to update all metadata YAML files to ensure standardized schema.
"""

import yaml
from pathlib import Path

meta_dir = Path("data/metadata")
meta_dir.mkdir(parents=True, exist_ok=True)

datasets = {
    "ppmi": {
        "dataset_id": "ppmi",
        "name": "Parkinson's Progression Markers Initiative",
        "source": "Michael J. Fox Foundation / LONI Image Data Archive",
        "official_source": "Michael J. Fox Foundation / LONI Image Data Archive",
        "access_requirements": "Account registration, research plan submission, and signed PPMI Data Use Agreement (DUA)",
        "license": "PPMI Data Use Agreement",
        "category": "A",
        "category_name": "same_participant_multimodal",
        "category_description": "Category A: Same-Participant Multimodal Data (True same-subject longitudinal multi-modality cohort)",
        "modalities": [
            "olfactory",
            "rbd_sleep",
            "motor_gait",
            "voice_speech",
            "biospecimens",
            "imaging",
        ],
        "participants": "4000+",
        "participant_count": "4000+",
        "labels": {
            "pd": "approx. 1500 (De Novo & Genetic PD)",
            "prodromal": "approx. 600 (RBD, Hyposmia, Genetic Risk)",
            "control": "approx. 800 (Healthy Controls)",
            "summary": "Clinical diagnosis: PD, Prodromal (RBD/Hyposmia), Healthy Control, SWEDD",
        },
        "pd_labels": "approx. 1500 (De Novo & Genetic PD)",
        "prodromal_labels": "approx. 600 (RBD, Hyposmia, Genetic Risk)",
        "control_labels": "approx. 800 (Healthy Controls)",
        "variables": [
            "PATNO",
            "EVENT_ID",
            "UPSIT_TOTAL",
            "RBDSQ_TOTAL",
            "NP3TOT",
            "DATSCAN_CAUDATE_R",
            "DATSCAN_PUTAMEN_R",
            "DIAGNOSIS",
        ],
        "file_format": "CSV, Parquet, DICOM, NIfTI",
        "file_formats": ["CSV", "Parquet", "DICOM", "NIfTI"],
        "missing_data": "Longitudinal attrition, optional sub-study non-completion, visit window missingness",
        "limitations": "Complex schema changes across annual data releases; restricted access for specific bio-assays (e.g. SAA)",
        "intended_use": "Primary dataset for prototype training, multimodal fusion development, and longitudinal validation",
        "local_path": "data/raw/ppmi/",
        "download_instructions": "Apply at https://www.ppmi-info.org/access-data-specimens/download-data, sign DUA, download tabular CSVs via LONI portal.",
        "status": "restricted",
    },
    "mpower": {
        "dataset_id": "mpower",
        "name": "Parkinson Disease Mobile Data Study (mPower)",
        "source": "Sage Bionetworks / Synapse Platform",
        "official_source": "Sage Bionetworks / Synapse Platform",
        "access_requirements": "Synapse user registration, human subjects research ethics training, and data access request",
        "license": "Synapse Qualified Researcher Governance Terms",
        "category": "A",
        "category_name": "same_participant_multimodal",
        "category_description": "Category A: Same-Participant Multimodal Mobile Data (High-frequency digital biomarker tasks)",
        "modalities": ["voice_speech", "motor_gait", "motor_tapping", "cognitive"],
        "participants": "10000+",
        "participant_count": "10000+",
        "labels": {
            "pd": "approx. 3000 (Self-reported PD diagnosis)",
            "prodromal": "unknown",
            "control": "approx. 7000 (Self-reported controls)",
            "summary": "Self-reported diagnosis (PD, Control) and medication timing (pre/post dose)",
        },
        "pd_labels": "approx. 3000 (Self-reported PD diagnosis)",
        "prodromal_labels": "unknown",
        "control_labels": "approx. 7000 (Self-reported controls)",
        "variables": [
            "recordId",
            "healthCode",
            "createdOn",
            "medTimepoint",
            "accel_gait.json",
            "tapping_results.json",
            "audio_phonation.m4a",
        ],
        "file_format": "CSV, JSON, m4a",
        "file_formats": ["CSV", "JSON", "m4a"],
        "missing_data": "High longitudinal participant attrition; missing task sessions",
        "limitations": "Self-reported diagnostic status; variable smartphone sensor quality; high noise",
        "intended_use": "Large-scale self-supervised pretraining for mobile digital biomarkers",
        "local_path": "data/raw/mpower/",
        "download_instructions": "Register at Synapse (https://www.synapse.org/#!Synapse:syn4993293), complete ethics verification, download via Synapse Python client.",
        "status": "restricted",
    },
    "uci_voice": {
        "dataset_id": "uci_voice",
        "name": "UCI Parkinson's Telemonitoring Dataset",
        "source": "UCI Machine Learning Repository / University of Oxford",
        "official_source": "UCI Machine Learning Repository / University of Oxford",
        "access_requirements": "None (Open Access)",
        "license": "CC BY 4.0",
        "category": "B",
        "category_name": "modality_specific",
        "category_description": "Category B: Modality-Specific Dataset (Acoustic speech dysphonia time-series)",
        "modalities": ["voice_speech"],
        "participants": "42",
        "participant_count": "42",
        "labels": {
            "pd": "42 (Early-stage PD patients monitored longitudinally)",
            "prodromal": "0",
            "control": "0",
            "summary": "Clinician-scored continuous motor_UPDRS (5-40) and total_UPDRS (7-55)",
        },
        "pd_labels": "42 (Early-stage PD patients monitored over 6 months)",
        "prodromal_labels": "0",
        "control_labels": "0",
        "variables": [
            "subject#",
            "age",
            "sex",
            "test_time",
            "motor_UPDRS",
            "total_UPDRS",
            "Jitter(%)",
            "Shimmer",
            "NHR",
            "HNR",
            "RPDE",
            "DFA",
            "PPE",
        ],
        "file_format": "CSV",
        "file_formats": ["CSV"],
        "missing_data": "Low missingness within acoustic features; uneven recording intervals per patient",
        "limitations": "Small subject count (N=42); lacks healthy control group; single modality (voice only)",
        "intended_use": "Modality-specific representation learning and regression target prediction for the speech/voice branch",
        "local_path": "data/raw/uci_voice/",
        "download_instructions": "Download directly from UCI Repository: https://archive.ics.uci.edu/dataset/189/parkinsons+telemonitoring",
        "status": "identified",
    },
    "physionet_gait": {
        "dataset_id": "physionet_gait",
        "name": "Gait in Parkinson's Disease Dataset",
        "source": "PhysioNet / Tel-Aviv Sourasky Medical Center",
        "official_source": "PhysioNet / Tel-Aviv Sourasky Medical Center",
        "access_requirements": "None (Open Access with standard citation)",
        "license": "Open Data Commons Attribution License (ODC-By) v1.0",
        "category": "B",
        "category_name": "modality_specific",
        "category_description": "Category B: Modality-Specific Dataset (Bilateral foot force sensor VGRF time-series)",
        "modalities": ["motor_gait"],
        "participants": "166",
        "participant_count": "166",
        "labels": {
            "pd": "93 (Clinically diagnosed Parkinson's Disease patients)",
            "prodromal": "0",
            "control": "73 (Healthy Controls)",
            "summary": "Binary PD vs Control diagnosis, Hoehn & Yahr staging, UPDRS motor scores",
        },
        "pd_labels": "93 (Parkinson's Disease patients)",
        "prodromal_labels": "0",
        "control_labels": "73 (Healthy Controls)",
        "variables": [
            "Time",
            "L1",
            "L2",
            "L3",
            "L4",
            "L5",
            "L6",
            "L7",
            "L8",
            "R1",
            "R2",
            "R3",
            "R4",
            "R5",
            "R6",
            "R7",
            "R8",
            "Total_Force_Left",
            "Total_Force_Right",
        ],
        "file_format": "TXT, CSV",
        "file_formats": ["TXT", "CSV"],
        "missing_data": "Minimal frame loss across 2-minute steady walking recordings",
        "limitations": "Single-modality gait force time-series; recorded under controlled laboratory conditions; no non-motor labels",
        "intended_use": "Modality-specific pretraining and feature extraction evaluation for the gait/motor branch",
        "local_path": "data/raw/physionet_gait/",
        "download_instructions": "Download from PhysioNet: https://physionet.org/content/gaitpdb/1.0.0/",
        "status": "identified",
    },
    "retinal_fundus_pretraining": {
        "dataset_id": "retinal_fundus_pretraining",
        "name": "Retinal Fundus Pretraining Corpus (EyePACS / Messidor-2 / DRIVE / APTOS)",
        "source": "Kaggle / Grand-Challenge.org / DRiDB",
        "official_source": "Kaggle / Grand-Challenge.org / DRiDB",
        "access_requirements": "Kaggle user registration and competition terms agreement",
        "license": "Custom Academic / Non-Commercial / CC-BY-NC",
        "category": "C",
        "category_name": "pretraining",
        "category_description": "Category C: Pretraining Dataset (Retinal fundus photography; CONTAINS NO PD LABELS)",
        "modalities": ["retina_fundus"],
        "participants": "40000+",
        "participant_count": "40000+",
        "labels": {
            "pd": "0 (Contains NO Parkinson's disease labels)",
            "prodromal": "0",
            "control": "0",
            "summary": "Diabetic retinopathy severity grades (0-4) and vessel segmentation masks; NO PD LABELS",
        },
        "pd_labels": "0 (Contains NO Parkinson's disease labels)",
        "prodromal_labels": "0",
        "control_labels": "0",
        "variables": ["image_id", "eye", "dr_grade", "vessel_mask"],
        "file_format": "JPEG, PNG, TIFF",
        "file_formats": ["JPEG", "PNG", "TIFF"],
        "missing_data": "Non-uniform image sizing, illumination gradients, media opacities",
        "limitations": "Strictly pretraining only; contains diabetic retinopathy and normal eye images but NO Parkinson's clinical labels",
        "intended_use": "Pretraining CNN / Vision Transformer backbones for retinal vessel segmentation and feature representation",
        "local_path": "data/raw/retinal_fundus_pretraining/",
        "download_instructions": "Download via Kaggle CLI: kaggle competitions download -c diabetic-retinopathy-detection",
        "status": "pretraining_only",
    },
    "oct500": {
        "dataset_id": "oct500",
        "name": "OCT500 Retinal Optical Coherence Tomography Dataset",
        "source": "Nanjing University of Science and Technology / IEEE DataPort",
        "official_source": "Nanjing University of Science and Technology / IEEE DataPort",
        "access_requirements": "Academic email registration and non-commercial end-user agreement",
        "license": "Academic Non-Commercial License",
        "category": "C",
        "category_name": "pretraining",
        "category_description": "Category C: Pretraining Dataset (Retinal OCT/OCTA volumetric scans; CONTAINS NO PD LABELS)",
        "modalities": ["retina_oct", "retina_octa"],
        "participants": "500",
        "participant_count": "500",
        "labels": {
            "pd": "0 (Contains NO Parkinson's disease labels)",
            "prodromal": "0",
            "control": "0",
            "summary": "Ophthalmic pathology labels (AMD, DR, CNV, Normal) and 6-layer retinal segmentations; NO PD LABELS",
        },
        "pd_labels": "0 (Contains NO Parkinson's disease labels)",
        "prodromal_labels": "0",
        "control_labels": "0",
        "variables": [
            "subject_id",
            "oct_volume",
            "foveal_thickness",
            "retinal_nerve_fiber_layer_mask",
        ],
        "file_format": "MAT, NIfTI, PNG",
        "file_formats": ["MAT", "NIfTI", "PNG"],
        "missing_data": "Low SNR frames in deeper choroidal scans",
        "limitations": "Contains retinal disease labels (AMD, DR, CNV) but NO Parkinson's disease labels; small sample size (N=500)",
        "intended_use": "Pretraining 3D OCT layer segmentation and retinal nerve fiber layer (RNFL) encoder models",
        "local_path": "data/raw/oct500/",
        "download_instructions": "Register at http://mmlab.eecs.umich.edu/oct500/ and request download link.",
        "status": "pretraining_only",
    },
    "predict_pd": {
        "dataset_id": "predict_pd",
        "name": "PREDICT-PD Study Cohort",
        "source": "Queen Mary University of London (QMUL) / University College London (UCL)",
        "official_source": "Queen Mary University of London (QMUL) / University College London (UCL)",
        "access_requirements": "Formal collaboration application to study PIs (predictpd@qmul.ac.uk) and institutional ethics committee approval",
        "license": "Institutional Data Transfer Agreement (DTA)",
        "category": "D",
        "category_name": "external_validation",
        "category_description": "Category D: External Validation Dataset (UK general population prodromal risk screening cohort)",
        "modalities": ["olfactory", "rbd_sleep", "motor_tapping", "non_motor_risk"],
        "participants": "10000+",
        "participant_count": "10000+",
        "labels": {
            "pd": "Incident PD cases tracked longitudinally",
            "prodromal": "approx. 500 (High-risk prodromal tier)",
            "control": "approx. 8000+ (Low-risk general population controls)",
            "summary": "Predicted PD risk algorithm tier (High / Intermediate / Low) and longitudinal motor conversion",
        },
        "pd_labels": "Incident PD cases tracked longitudinally",
        "prodromal_labels": "approx. 500 (High-risk prodromal tier)",
        "control_labels": "approx. 8000+ (Low-risk general population controls)",
        "variables": [
            "participant_id",
            "upsit_score",
            "kbd_tapping_speed",
            "rbd_score",
            "pd_risk_tier",
        ],
        "file_format": "CSV, Tabular",
        "file_formats": ["CSV", "Tabular"],
        "missing_data": "Self-administered online questionnaire missingness; longitudinal drop-off",
        "limitations": "Not available for open public download; keyboard tapping is less precise than clinical force sensors",
        "intended_use": "External validation dataset for prodromal risk stratification and non-motor algorithm testing",
        "local_path": "data/raw/predict_pd/",
        "download_instructions": "Submit formal research proposal to predictpd@qmul.ac.uk; execute institutional DTA.",
        "status": "restricted",
    },
    "synthetic_fixture": {
        "dataset_id": "synthetic_fixture",
        "name": "MPF-PD Synthetic Test Fixture",
        "source": "MPF-PD Internal Data Pipeline Generator",
        "official_source": "MPF-PD Internal Data Pipeline Generator",
        "access_requirements": "None (Public internally generated fixture)",
        "license": "MIT License",
        "category": "E",
        "category_name": "synthetic_fixture",
        "category_description": "Category E: Synthetic Test Fixture (Artificially generated mock multi-biomarker cohort strictly for CI/CD)",
        "modalities": [
            "olfactory",
            "rbd_sleep",
            "motor_gait",
            "voice_speech",
            "retina_fundus",
        ],
        "participants": "100",
        "participant_count": "100",
        "labels": {
            "pd": "35 (Synthetic mock PD class)",
            "prodromal": "30 (Synthetic mock Prodromal class)",
            "control": "35 (Synthetic mock Control class)",
            "summary": "Synthetic integer labels (0=Control, 1=Prodromal, 2=PD); ZERO clinical validity",
        },
        "pd_labels": "35 (Synthetic mock PD class)",
        "prodromal_labels": "30 (Synthetic mock Prodromal class)",
        "control_labels": "35 (Synthetic mock Control class)",
        "variables": [
            "participant_id",
            "upsit_score",
            "rbd_score",
            "updrs_motor",
            "voice_pitch_sd",
            "retinal_rnfl_thickness",
            "diagnosis",
        ],
        "file_format": "CSV, Parquet",
        "file_formats": ["CSV", "Parquet"],
        "missing_data": "Controlled synthetic missingness (10% missing values per column)",
        "limitations": "Purely synthetic test fixture; contains zero physiological reality or real patient evidence",
        "intended_use": "Unit testing, continuous integration, and pipeline validation",
        "local_path": "tests/fixtures/synthetic_fixture.csv",
        "download_instructions": "Generated programmatically by running test suite scripts.",
        "status": "synthetic_fixture",
    },
}

for ds_id, data in datasets.items():
    file_path = meta_dir / f"{ds_id}.yaml"
    with open(file_path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    print(f"Wrote {file_path}")

print("Successfully updated all 8 metadata YAML files.")
